site_name: Siddhi Execution TensorFlow
site_description: Siddhi Execution TensorFlow Extension
repo_name: Siddhi Execution Tensorflow
repo_url: https://github.com/siddhi-io/siddhi-execution-tensorflow/
edit_uri: https://github.com/siddhi-io/siddhi-execution-tensorflow/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Information: index.md
- API Docs:
  - latest: api/latest.md
  - 2.0.1: api/2.0.1.md
  - 2.0.0: api/2.0.0.md
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.8: api/1.0.8.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
- License: license.md
