site_name: Siddhi Execution TensorFlow
site_description: Siddhi Execution TensorFlow Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-execution-tensorflow/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-Execution-TensorFlow
repo_url: https://github.com/wso2-extensions/siddhi-execution-tensorflow
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.8: api/1.0.8.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
  - latest: api/latest.md
- License: LICENSE.md
